# Generated by Django 3.2.7 on 2022-01-19 09:35

import core.frame.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eng_name', models.CharField(max_length=100, verbose_name='영문캐릭터명')),
                ('kor_name', models.CharField(max_length=200, verbose_name='한글캐릭터명')),
                ('description', models.TextField(verbose_name='캐릭터 설명')),
                ('defence', models.FloatField(verbose_name='방어')),
                ('guts', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='근성치')),
                ('prejump', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='점프이행')),
                ('backdash', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='백대시프레임')),
                ('backdash_invuln', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='백대시무적')),
                ('weight', models.CharField(choices=[('Light', 'Light'), ('Normal', 'Normal'), ('Heavy', 'Heavy')], max_length=10, verbose_name='무게')),
            ],
            options={
                'verbose_name': '캐릭터',
                'verbose_name_plural': '캐릭터',
                'db_table': 'character',
            },
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(max_length=100, verbose_name='가드방향')),
            ],
            options={
                'verbose_name': '가드방향',
                'verbose_name_plural': '가드방향',
                'db_table': 'guard',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=100, verbose_name='커맨드')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='기술명')),
                ('damage', models.IntegerField(verbose_name='데미지')),
                ('start', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='이행프레임')),
                ('active', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='지속프레임')),
                ('recovery', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='회복프레임')),
                ('on_block', models.IntegerField(verbose_name='가드시프레임')),
                ('description', models.TextField(blank=True, null=True, verbose_name='기술 설명')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move', to='frame.character', verbose_name='캐릭터')),
            ],
            options={
                'verbose_name': '기술',
                'verbose_name_plural': '기술',
                'db_table': 'move',
            },
        ),
        migrations.CreateModel(
            name='MoveGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frame.guard', verbose_name='가드방향')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frame.move', verbose_name='기술')),
            ],
            options={
                'db_table': 'move_guard',
            },
        ),
        migrations.CreateModel(
            name='MoveFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.frame.models.upload_to, verbose_name='이미지')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_image', to='frame.move', verbose_name='기술')),
            ],
            options={
                'verbose_name': '기술이미지',
                'verbose_name_plural': '기술이미지',
                'db_table': 'move_file',
            },
        ),
        migrations.AddField(
            model_name='move',
            name='guard',
            field=models.ManyToManyField(through='frame.MoveGuard', to='frame.Guard', verbose_name='가드방향'),
        ),
    ]
