# Generated by Django 3.2.7 on 2022-02-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='eng_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='영문캐릭터명'),
        ),
        migrations.AlterField(
            model_name='character',
            name='kor_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='한글캐릭터명'),
        ),
    ]
